### ISSUE TITLE
unmet dependency

### ISSUE THREAD

**Issue by tonywoode** [laggingreflex/mochista#1]
I npm installed mochista 0.4.1 running on node 6.8.0 and npm 3.10.8 and received: 

```
{ Error: Cannot find module 'ority'
    at Function.Module._resolveFilename [as __resolveFilename] (module.js:469:15)
    at Function.requireUpPatch [as _resolveFilename] (/Users/twoode/my_project/node_modules/require-up/register.js:19:16)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/twoode/my_project/node_modules/mochista/src/utils/pad.js:1:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at requireUp (/Users/twoode/my_project/node_modules/require-up/index.js:32:22)
    at Function.requireUpPatch [as _resolveFilename] (/Users/twoode/my_project/node_modules/require-up/register.js:13:18)
    at Function.Module._load (module.js:417:25) code: 'MODULE_NOT_FOUND' }
```
An `npm install --save-dev ority` fixes this

**Comment by laggingreflex** [comment]
Thanks! fixed. 0.4.2
