### ISSUE TITLE
TypeError: Object.entries is not a function

### ISSUE THREAD

**Issue by KenFigueiredo** [laggingreflex/mochista#8]
Any ideas what could be causing this?
Using `node v6.8.0`

I'm getting this error after globally installing:

```
TypeError: Object.entries is not a function
    at exports.config (/usr/local/lib/node_modules/mochista/src/utils/logger/index.js:13:35)
    at createLogger (/usr/local/lib/node_modules/mochista/src/utils/logger/index.js:27:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/mochista/src/utils/logger/index.js:39:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
Couldn't require "dist/bin", trying "src/bin"...
{ Error: Cannot find module './src/bin'
    at Function.Module._resolveFilename [as __resolveFilename] (module.js:469:15)
    at Function.requireUpPatch [as _resolveFilename] (/usr/local/lib/node_modules/mochista/node_modules/require-up/register.js:19:16)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/mochista/bin.js:14:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12) code: 'MODULE_NOT_FOUND' }
Couldn't require "src" either. Try compiling or use with 'babel-register' or `--harmony` flag
```

**Comment by laggingreflex** [comment]
Ah sorry, `babel-polyfill` wasn't included. Fixed in v0.9.2 (https://github.com/laggingreflex/mochista/commit/9493e753d984aa52e4dca6ceb81397e440c318ba)
